"""Partial solution: ordered assignment list with decision levels.

The partial solution is a chronological trail of assignments.  Each
assignment constrains a package's allowed versions and is either a
decision (the resolver picks a specific version to try) or a
derivation (a constraint deduced by unit propagation).

Each decision opens a new "decision level".  Backtracking removes
all assignments above a target level, which is cheaper than copying
the entire state on every decision.

Reference: https://github.com/dart-lang/pub/blob/master/doc/solver.md#partial-solution
"""

from __future__ import annotations

from collections import defaultdict
from typing import TYPE_CHECKING, Any, Generic

from .ranges import Range
from .types import PackageType, RangeProtocol, VersionType

if TYPE_CHECKING:
    from collections.abc import Sequence

    from .types import Incompatibility, Term


__all__ = [
    "Assignment",
    "PartialSolution",
]


# Distinguishes "cached miss" from a legitimate cached None.
_UNSET = object()


class Assignment(Generic[PackageType, VersionType]):
    """A single entry in the partial solution trail."""

    # Written out rather than generated by ``dataclasses`` so the resolver
    # does not import that module (cpip patch, see VENDORED.md).
    __slots__ = (
        "_effective",
        "accumulated_range",
        "cause",
        "cum_decision",
        "cum_negative",
        "cum_positive",
        "decision_level",
        "is_decision",
        "package",
        "positive",
        "trail_index",
        "version",
    )

    package: PackageType
    """Which package this assignment constrains."""

    accumulated_range: RangeProtocol[VersionType]
    """The cumulative range for this package at the time of assignment."""

    decision_level: int
    """The decision depth when this assignment was made."""

    is_decision: bool
    """True if this is a version choice; False if derived by propagation."""

    trail_index: int
    """Chronological position in the assignment trail."""

    version: VersionType | None
    """The chosen version (only set for decisions)."""

    cause: Incompatibility[PackageType, VersionType] | None
    """The incompatibility that forced this derivation (only for derivations)."""

    positive: bool
    """Whether this constrains the package positively or negatively."""

    cum_positive: RangeProtocol[VersionType] | None
    """Latest positive accumulated range for the package as of this entry."""

    cum_negative: RangeProtocol[VersionType] | None
    """Latest negative accumulated range for the package as of this entry."""

    cum_decision: VersionType | None
    """The package's decided version as of this entry, if it had one."""

    _effective: RangeProtocol[VersionType] | None
    """Cached ``cum_positive - cum_negative``, lazily computed by
    ``PartialSolution._satisfied_at``. ``cum_positive``/``cum_negative`` are
    fixed once an assignment is on the trail, so the combined range never
    changes -- but ``satisfier``'s binary search can probe the same trail
    entry many times across conflict analysis, and the subtraction it
    otherwise repeats is one of the more expensive Range operations."""

    def __init__(
        self,
        package: PackageType,
        accumulated_range: RangeProtocol[VersionType],
        decision_level: int,
        is_decision: bool,
        trail_index: int = 0,
        version: VersionType | None = None,
        cause: Incompatibility[PackageType, VersionType] | None = None,
        positive: bool = True,
        cum_positive: RangeProtocol[VersionType] | None = None,
        cum_negative: RangeProtocol[VersionType] | None = None,
        cum_decision: VersionType | None = None,
    ) -> None:
        self.package = package
        self.accumulated_range = accumulated_range
        self.decision_level = decision_level
        self.is_decision = is_decision
        self.trail_index = trail_index
        self.version = version
        self.cause = cause
        self.positive = positive
        self.cum_positive = cum_positive
        self.cum_negative = cum_negative
        self.cum_decision = cum_decision
        self._effective = None

    def _values(self) -> tuple[object, ...]:
        return (
            self.package,
            self.accumulated_range,
            self.decision_level,
            self.is_decision,
            self.trail_index,
            self.version,
            self.cause,
            self.positive,
            self.cum_positive,
            self.cum_negative,
            self.cum_decision,
        )

    def __eq__(self, other: object) -> bool:
        return type(other) is Assignment and self._values() == other._values()

    __hash__ = None  # type: ignore[assignment]

    def __repr__(self) -> str:
        return (
            f"Assignment(package={self.package!r}, "
            f"accumulated_range={self.accumulated_range!r}, "
            f"decision_level={self.decision_level!r}, "
            f"is_decision={self.is_decision!r}, trail_index={self.trail_index!r}, "
            f"version={self.version!r}, cause={self.cause!r}, "
            f"positive={self.positive!r}, cum_positive={self.cum_positive!r}, "
            f"cum_negative={self.cum_negative!r}, cum_decision={self.cum_decision!r})"
        )


class PartialSolution(Generic[PackageType, VersionType]):
    """Tracks the resolver's current partial solution as a decision trail.

    This is the PubGrub equivalent of a SAT solver's assignment trail.
    See: https://en.wikipedia.org/wiki/Conflict-driven_clause_learning#Organization
    """

    def __init__(self, range_type: type[RangeProtocol[Any]] = Range) -> None:
        """Initialize an empty partial solution."""
        self._range_type = range_type
        self._assignments: list[Assignment[PackageType, VersionType]] = []
        self._decision_level = 0
        self._positive_ranges: dict[PackageType, RangeProtocol[VersionType]] = {}
        self._negative_ranges: dict[PackageType, RangeProtocol[VersionType]] = {}
        self._decided_versions: dict[PackageType, VersionType] = {}

        # Incrementally maintained as set(positive) - set(decided).
        self._undecided: set[PackageType] = set()

        # Memoises positive - negative per package.
        self._effective_range_cache: dict[
            PackageType, RangeProtocol[VersionType] | None
        ] = {}

        # Packages whose range moved since the last drain. ``prioritize`` is
        # handed a package's range, so a decision scan that reuses a cached
        # sort key has to know which ones it may no longer trust.
        self._touched: set[PackageType] = set()

        # Per-package index of trail entries; lets satisfier() avoid the full scan.
        self._assignments_by_package: defaultdict[
            PackageType, list[Assignment[PackageType, VersionType]]
        ] = defaultdict(list)

    @property
    def decision_level(self) -> int:
        """Return the current decision depth."""
        return self._decision_level

    @property
    def trail_length(self) -> int:
        """Return the number of assignments currently on the trail."""
        return len(self._assignments)

    def assignments_for(
        self, package: PackageType
    ) -> Sequence[Assignment[PackageType, VersionType]]:
        """Return the chronological assignment trail for ``package``.

        Read-only view; callers must not mutate the result.
        """
        entries = self._assignments_by_package.get(package)
        if entries is None:
            return ()
        return entries

    def get(self, package: PackageType) -> RangeProtocol[VersionType] | None:
        """Get the combined allowed range for a package, or None if unassigned.

        Computes ``positive - negative``, cached per package.
        """
        cached = self._effective_range_cache.get(package, _UNSET)
        if cached is not _UNSET:
            return cached  # type: ignore[return-value]  # typing.cast is a call on the hottest read

        positive = self._positive_ranges.get(package)
        negative = self._negative_ranges.get(package)

        if positive is None and negative is None:
            result: RangeProtocol[VersionType] | None = None
        elif positive is None:
            # No requirement to subtract from. An exclusion-only package is
            # never offered for selection, so the plain complement is enough.
            assert negative is not None
            result = ~negative
        elif negative is None:
            result = positive
        else:
            result = positive - negative

        self._effective_range_cache[package] = result
        return result

    def decide(self, package: PackageType, version: VersionType) -> None:
        """Record a decision: pick a specific version for a package."""
        self._decision_level += 1
        exact_range = self._range_type.singleton(version)

        self._positive_ranges[package] = exact_range
        self._decided_versions[package] = version
        self._effective_range_cache.pop(package, None)
        self._undecided.discard(package)
        self._touched.add(package)

        package_entries = self._assignments_by_package[package]
        assignment = Assignment(
            package=package,
            accumulated_range=exact_range,
            decision_level=self._decision_level,
            is_decision=True,
            trail_index=len(self._assignments),
            version=version,
            positive=True,
            cum_positive=exact_range,
            cum_negative=self._negative_ranges.get(package),
            cum_decision=version,
        )
        self._assignments.append(assignment)
        package_entries.append(assignment)

    def derive(
        self,
        package: PackageType,
        constraint: RangeProtocol[VersionType],
        *,
        positive: bool,
        cause: Incompatibility[PackageType, VersionType],
    ) -> None:
        """Record a derivation from unit propagation.

        See: https://github.com/dart-lang/pub/blob/master/doc/solver.md#unit-propagation
        """
        if positive:
            # Positive derivation narrows the package's allowed range.
            if package in self._positive_ranges:
                new_range = self._positive_ranges[package] & constraint
            else:
                new_range = self._range_type.full() & constraint
            self._positive_ranges[package] = new_range
            if package not in self._decided_versions:
                self._undecided.add(package)
        else:
            # Negative derivation accumulates excluded versions.
            if package in self._negative_ranges:
                new_range = self._negative_ranges[package] | constraint
            else:
                new_range = self._range_type.empty() | constraint
            self._negative_ranges[package] = new_range

        self._effective_range_cache.pop(package, None)
        self._touched.add(package)

        package_entries = self._assignments_by_package[package]
        assignment = Assignment(
            package=package,
            accumulated_range=new_range,
            decision_level=self._decision_level,
            is_decision=False,
            trail_index=len(self._assignments),
            cause=cause,
            positive=positive,
            cum_positive=self._positive_ranges.get(package),
            cum_negative=self._negative_ranges.get(package),
            cum_decision=self._decided_versions.get(package),
        )
        self._assignments.append(assignment)
        package_entries.append(assignment)

    def backtrack(self, target_level: int) -> None:
        """Remove all assignments above target_level.

        Non-chronological backjumping: skips past irrelevant decision levels
        directly to the cause of the conflict.  Every ``cum_*`` field records
        the package's state as of that entry, so the surviving top entry
        restores it outright -- no re-intersecting, and no rescan of the
        package's trail.
        See: https://github.com/dart-lang/pub/blob/master/doc/solver.md#conflict-resolution
        """
        affected_packages: set[PackageType] = set()
        while self._assignments and self._assignments[-1].decision_level > target_level:
            assignment = self._assignments.pop()
            package = assignment.package
            affected_packages.add(package)

            entries = self._assignments_by_package.get(package)
            if entries:
                entries.pop()

        self._decision_level = target_level
        self._touched |= affected_packages

        for package in affected_packages:
            entries = self._assignments_by_package.get(package)
            if not entries:
                self._assignments_by_package.pop(package, None)
                self._positive_ranges.pop(package, None)
                self._negative_ranges.pop(package, None)
                self._decided_versions.pop(package, None)
                self._undecided.discard(package)
            else:
                last_entry = entries[-1]

                if last_entry.cum_positive is None:
                    self._positive_ranges.pop(package, None)
                else:
                    self._positive_ranges[package] = last_entry.cum_positive

                if last_entry.cum_negative is None:
                    self._negative_ranges.pop(package, None)
                else:
                    self._negative_ranges[package] = last_entry.cum_negative

                decided_version = last_entry.cum_decision
                if decided_version is None:
                    self._decided_versions.pop(package, None)
                else:
                    self._decided_versions[package] = decided_version

                if last_entry.cum_positive is not None and decided_version is None:
                    self._undecided.add(package)
                else:
                    self._undecided.discard(package)

        self._effective_range_cache.clear()

    def drain_touched(self) -> set[PackageType]:
        """Return packages whose range moved since the last call, and reset.

        ``decide``, ``derive`` and ``backtrack`` are the only writers of a
        package's range, so recording here is what keeps a cached sort key
        from outliving the range it was built from.
        """
        touched = self._touched
        self._touched = set()
        return touched

    def decisions(self) -> dict[PackageType, VersionType]:
        """Return the current decision map: ``{package: version}``."""
        return dict(self._decided_versions)

    def undecided_packages(self) -> set[PackageType]:
        """Return packages with positive constraints but no decision yet.

        Packages with only negative derivations (learned exclusions) are not
        yet known to be required.  Returns a fresh copy so callers can mutate
        without disturbing solver state.
        """
        return set(self._undecided)

    def has_positive_constraint(self, package: PackageType) -> bool:
        """Return True if the package has a positive constraint or decision."""
        return package in self._positive_ranges or package in self._decided_versions

    def positive_ranges(self) -> dict[PackageType, RangeProtocol[VersionType]]:
        """Return a copy of the positive-range map for each package."""
        return dict(self._positive_ranges)

    def positive_range(self, package: PackageType) -> RangeProtocol[VersionType] | None:
        """Return the package's accumulated positive range, or None if unset."""
        return self._positive_ranges.get(package)

    def _satisfied_at(
        self,
        assignment: Assignment[PackageType, VersionType],
        term: Term[PackageType, VersionType],
        *,
        is_positive: bool,
    ) -> bool:
        """Whether the trail up to and including ``assignment`` satisfies term.

        Positive terms need a positive assignment first; negatives alone
        only exclude versions.
        """
        cum_positive = assignment.cum_positive
        if is_positive and cum_positive is None:
            return False

        effective = assignment._effective
        if effective is None:
            if cum_positive is None:
                assert assignment.cum_negative is not None
                effective = ~assignment.cum_negative
            elif assignment.cum_negative is None:
                effective = cum_positive
            else:
                effective = cum_positive - assignment.cum_negative
            assignment._effective = effective

        return term.satisfies(effective)

    def satisfier(
        self, term: Term[PackageType, VersionType]
    ) -> Assignment[PackageType, VersionType] | None:
        """Find the earliest assignment that causes the term to be satisfied.

        The effective range only narrows along the trail, so ``term.satisfies``
        is monotonic: once an entry satisfies the term, every later one does
        too.  That lets a binary search replace the linear scan.
        See: https://github.com/dart-lang/pub/blob/master/doc/solver.md#conflict-resolution
        """
        entries = self._assignments_by_package.get(term.package, ())
        count = len(entries)
        if count == 0:
            return None

        is_positive = term.is_positive()
        if not self._satisfied_at(entries[count - 1], term, is_positive=is_positive):
            return None

        low, high = 0, count - 1
        while low < high:
            mid = (low + high) // 2
            if self._satisfied_at(entries[mid], term, is_positive=is_positive):
                high = mid
            else:
                low = mid + 1
        return entries[low]
